image:
  pullPolicy: IfNotPresent
  repository: stonith404/pingvin-share
  tag: v0.21.2@sha256:bc8cea3df3a22653ef614c521938ce8f3feeb2ce88f709b69d8e28c501489a56
persistence:
  data:
    enabled: true
    mountPath: /opt/app/backend/data
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10595
        protocol: http
        targetPort: 3000
