image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/linuxserver/darktable
  tag: 4.0.1@sha256:63dcf4384340f2bf43c87ae41534c3d9dcb90e6d7f5fe03beae4dd46f1ecf83e
persistence:
  config:
    enabled: true
    mountPath: /config
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10129
        targetPort: 3000
