image:
  pullPolicy: IfNotPresent
  repository: ydkn/cups
  tag: latest@sha256:fa8def8258e85b76bcd0fa6603247e22d3e731cacd6a54a0b7ea7f5d0b8756d0
persistence:
  config:
    enabled: true
    mountPath: /etc/cups
  dbus:
    enabled: true
    hostPath: /var/run/dbus
    mountPath: /var/run/dbus
    readOnly: false
    type: hostPath
portal:
  open:
    enabled: true
securityContext:
  container:
    container:
      readOnlyRootFilesystem: false
      runAsGroup: 0

      runAsUser: 0
service:
  main:
    ports:
      main:
        port: 631
        protocol: http
        targetPort: 631
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ADMIN_PASSWORD: secretpass
