cnpg:
  main:
    acceptRO: false
    creds: {}
    database: app
    enabled: false
    instances: 2
    monitoring:
      enablePodMonitor: true
    pooler:
      instances: 2
    primary: true
    primaryUpdateStrategy: unsupervised
    storage:
      size: 256Gi
      walsize: 256Gi
    user: app
image:
  pullPolicy: IfNotPresent
  repository: bitnami/postgresql
  tag: 14.10.0@sha256:90e79c0c1509fc47d6c46715ec928467868e133d83a1eddb23c3589b036042dd
portal:
  open:
    enabled: false
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
        port: 9999
workload:
  main:
    enabled: false
    podSpec:
      containers:
        main:
          enabled: false
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
